#!/usr/bin/env -S PYTHONPATH=../../../tools/extract-utils python3
# SPDX-License-Identifier: Apache-2.0
# H1A1000 / HydrogenONE LineageOS 22.2 bring-up extraction scaffold.

from extract_utils.fixups_blob import blob_fixup, blob_fixups_user_type
from extract_utils.fixups_lib import lib_fixups
from extract_utils.main import ExtractUtils, ExtractUtilsModule

# Generated by analyzing the supplied stock Android 8.1 vendor ELF DT_NEEDED entries.
from tools.legacy_hidl_fixup_paths import (
    HIDL_BASE_ONLY,
    HIDL_BASE_TRANSPORT,
    HIDL_BASE_TRANSPORT_HWBINDER,
)

namespace_imports = [
    'device/red/hydrogenone',
    'hardware/qcom-caf/msm8998',
    'hardware/qcom-caf/wlan',
    'vendor/qcom/opensource/data-ipa-cfg-mgr-legacy-um',
    'vendor/qcom/opensource/dataservices',
]

# Android 8.1 split HIDL transport ABI -> compatibility lib used by modern Lineage ports.
# The 3 rare binaries that reference transport/hwbinder without libhidlbase are NOT auto-fixed
# here; handle them after the first linker log instead of guessing.
blob_fixups: blob_fixups_user_type = {
}

module = ExtractUtilsModule(
    'hydrogenone',
    'red',
    blob_fixups=blob_fixups,
    lib_fixups=lib_fixups,
    namespace_imports=namespace_imports,
)

if __name__ == '__main__':
    ExtractUtils.device(module).run()
